In [47]:
import math
def basic_sigmoid(x):
    # """
    # Compute sigmoid of x.

    # Arguments:
    # x -- A Scalar

    # Return:
    # s -- sigmoid(x)
    # """

    s = 1 / (1 + math.exp(-x))
    return s

In [49]:
basic_sigmoid(-1)

0.2689414213699951

In [51]:
import numpy as np
x=np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [53]:
x=np.array([1,2,3])
print(x+3)

[4 5 6]


In [75]:
import numpy as np
def basic_sigmoid(x):
    s = 1 / (1 + np.exp(-x))
    return s

In [77]:
basic_sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [113]:
def gradient_sigmoid(x):
    gs = basic_sigmoid(x)*(1-basic_sigmoid(x))
    return gs

In [115]:
gradient_sigmoid(x)

array([0.19661193, 0.10499359, 0.04517666])

In [137]:
def image2vector(image):
    v=image.reshape((image.shape[0]*image.shape[1]*image.shape[2],1))
    return v

In [143]:
image = np.array([[[0.67, 0.29],
                   [0.90, 0.52],
                   [0.42, 0.45]],

                   [[0.56, 0.45],
                    [0.90, 0.89],
                    [0.27, 0.58]],

                    [[0.45, 0.96],
                     [0.87, 0.66],
                     [0.73, 0.25]]])

print("image2vector(image) = " + str(image2vector(image)))                    

image2vector(image) = [[0.67]
 [0.29]
 [0.9 ]
 [0.52]
 [0.42]
 [0.45]
 [0.56]
 [0.45]
 [0.9 ]
 [0.89]
 [0.27]
 [0.58]
 [0.45]
 [0.96]
 [0.87]
 [0.66]
 [0.73]
 [0.25]]


In [145]:
def normalizeRows(x):
    x_norm = np.linalg.norm(x,axis = 1, keepdims = True)
    x = x/x_norm #matrix/vector
    return x	  

In [147]:
x=np.array([[0, 1000, 4],
            [2, 6, 4]])
print(str(normalizeRows(x)))

[[0.         0.999992   0.00399997]
 [0.26726124 0.80178373 0.53452248]]


In [149]:
def softmax(x):

    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    s = x_exp / x_sum
    
    return s

In [163]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0, 0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [180]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print(str(dot)+"\n"+ str(1000*(toc-tic))+"ms")


278
0.0ms


In [182]:
# VECTORIZED DOT IMPLEMENTATION
tic = time.process_time()
dot=np.dot(x1,x2)
toc=time.process_time()
print("dot="+str(dot)+"---computation time="+str(1000*(toc-tic))+"ms")


dot=278---computation time=0.0ms
